### ISSUE TITLE
Is it possible to get end to end traces for aws serverless lambda, for all possible triggers otherthan AWS Gateway?

### ISSUE THREAD

**Issue by bala1074** [DataDog/datadog-lambda-js#119]
Is it possible to get end to end traces for aws serverless lambda, for all possible triggers otherthan AWS Gateway?

I tested with aws x-ray, it is supporting traces for AWS Gateway and Lambda correlation.

But I was stuck at other possible lambda triggers.

Does datadog agent supports CloudwatchEvents, Log Subscriptions, DynamoDb Streams, S3 file triggers ..etc., triggers to lambda.

I need to derive correlation for all possible lambda triggers.
trigger(API Gateway or Streams or Events..) --------------> Lmabda ---------------> DynamoDB

**Comment by 1inuxoid** [comment]
Hey @bala1074 I think you want to have a look at DAZN power tools:
https://github.com/getndazn/dazn-lambda-powertools/tree/master/packages/lambda-powertools-middleware-correlation-ids
https://github.com/getndazn/dazn-lambda-powertools/tree/master/packages/lambda-powertools-correlation-ids

**Comment by tianchu** [comment]
@bala1074 Sorry for the super late reply! If you upgrade to the latest `datadog-lambda-js` and have Datadog tracing enabled, you should be able to see the AWS resource that triggers each invocation within Datadog. 

Since this is more like a product question, I'm going to close it here. I do recommend you join our [Slack community](https://a.cl.ly/KouJGRLK), and I'm happy to show you what we have now and will have in the future, in terms of visibility into triggers and correlation. 

Thanks for your feedback, it definitely helps guide our future product improvement!
