### ISSUE TITLE
Unable to control service name of wrapped handlers

### ISSUE THREAD

**Issue by bigkraig** [DataDog/datadog-lambda-js#152]
## Expected Behavior
I'd like to be able to control the name of the service that appears in my facet list for the function that is traced. I've been unable to find a way to control this and its always named the function. My service is made up of many functions so this isn't very meaningful and adds junk to my facet list.

Thanks!

**Comment by tianchu** [comment]
@bigkraig Sorry for the really late reply and I hope you have already figured this out. Anyway, through the AWS integration, we crawl your Lambda tags and apply them to the ingested data in Datadog, and that's what powers the facet list. See https://docs.datadoghq.com/serverless/troubleshooting/serverless_tagging. In short, just add a `service` tag to your Lambda functions should do.

I'm closing this issue, since we didn't identify any generally applicable bug. But feel free to find us at https://chat.datadoghq.com/ (join the #serverless channel) for questions and contact Datadog Support if you need someone to take a deeper look at your set up.
