### ISSUE TITLE
Ability to override http request options

### ISSUE THREAD

**Issue by pdhodgkinson** [DataDog/datadog-lambda-js#158]
## Expected Behavior
Can somehow configure the underlying http(s) client to override values https://nodejs.org/api/http.html#http_http_request_options_callback

Specifically looking to set the timeout values to something lower than the default 120 seconds.
We have had cases, under high load, where the datadog client library would timeout and cause our lambdas (that were configured for less than 120 seconds execution time) to fail.

## Actual Behavior

Currently there is no way to set these values

**Comment by tianchu** [comment]
@pdhodgkinson do you have an error log or stack trace to help us understand the exact issue?

**Comment by pdhodgkinson** [comment]
@tianchu It's a feature request, not a bug report, but it's hard to describe via stack trace, which is why I didn't provide anything. But consider:

1. You have a lambda which has a configured timeout of 2 minutes (or less).
2. You utilize `sendDistributionMetrics` from this library, which in turn does a `POST` using the built-in node 'http' or 'https' library. The default connection timeout for the built-in node 'http' library is 120000ms or 2 minutes. 
3. The POST from step 2 runs into transient network issues such that no response arrives.
4. The lambda will timeout BEFORE the http connection times out and your lambda will error with an error like `Task timed out after 120.10 seconds` with no obvious reason why.

In my testing I extended the lambda timeout to 3 minutes and then received, after the 2 minute timeout `{"innerError":{},"status":"error","message":"datadog:failed to flush metrics"}`

The request is that ideally I could configure the datadog client to have a custom http timeout so that a lambda that is configured for less than 2 minutes runtime will be able to handle the error gracefully, and not cause the lambda to timeout.
E.g. I'd like to be able to set the timeout value  [here](https://github.com/DataDog/datadog-lambda-js/blob/dda60f21d0eb05e434424e4ca24a2e16953e09ed/src/utils/request.ts#L32)

**Comment by tianchu** [comment]
@pdhodgkinson Thanks for your comprehensive description, and it makes perfect sense to me!

Unfortunately this feature may not become a priority to our team, because we are focusing on the development of [Lambda extension](https://docs.datadoghq.com/serverless/datadog_lambda_library/extension/), and we expect most of customers submitting metrics synchronously to migrate to using the Lambda extension instead when it's GA.

That said, the changes required for your proposed feature may not be too bad, and if you have interest in [contributing](https://github.com/DataDog/datadog-lambda-js#contributing), you are more than welcome to submit a PR.

**Comment by pdhodgkinson** [comment]
@tianchu thanks for the feedback. Do you have insight on when the Lambda extension might be GA'd?

**Comment by tianchu** [comment]
@pdhodgkinson Sorry for the late reply, the Datadog Lambda Extension has been GA'd recently. You can find the updated installation instructions: https://docs.datadoghq.com/serverless/installation/nodejs?tab=serverlessframework. I'm closing the issue for now, since the Lambda Extension will be the future and where our development effort focuses on.
