### ISSUE TITLE
Yarn Berry + Webpack = datadog-lambda-js cannot require `aws-sdk`

### ISSUE THREAD

**Issue by dipack95** [DataDog/datadog-lambda-js#191]
## Expected Behavior

`datadog-lambda-js` should be able to `require()` `aws-sdk` in the KMS Service class.

## Actual Behavior

Currently see this error on function startup:

```
datadog:optional dependency aws-sdk not installed. KMS key decryption will not work
```

## Steps to Reproduce the Problem

It's difficult to reproduce this particular error, but hopefully I can explain it best I can in the comments.

Yarn berry provides us with a mapfile, that we must import into our code, to allow the `require()` function to resolve external dependencies (like `lodash`, etc.). We import it like `require('/path/to/mapfile.js').setup()` at the start of the bundled script, which allows the `require` module resolution to work as usual.

We also bundle our external dependencies as a lambda layer to avoid bloating the size of our bundle. We do not provide the `aws-sdk` package in our lambda layer as AWS already provides it `/var/runtime/node_modules/aws-sdk`.

With these things taken into account, we've started noticing that Datadog's Lambda layer complains about not being able to import the `aws-sdk`, even though I can see that a require for the SDK later on in our code works just fine. 

## Specifications

  - Datadog Lambda Layer version: Datadog-Node14-x, version 52
  - Node version: 14

**Comment by ddiprose** [comment]
I've noticed this as well (although not using webpack, but serverless + yarn.build bundler).

It appears to be caused by aws-sdk not being a peerDependency of this library, and the fact that yarn berry does not load libraries that have not been specified in a package's package.json file by default, as per it's security model.

I would suggest that aws-sdk be added to the datadog-lambda-js peerDependencies. A workaround for the time being may be to add a packageExtensions config entry into your .yarnrc.yml file, with aws-sdk being added as a peerDependency of datadog-lambda-js.

**Comment by dipack95** [comment]
Sorry for the late response to this @ddiprose, but your suggestion unfortunately did not work -- I added `aws-sdk` as a peer dependency to `datadog-lambda-js` like so:

```yaml
packageExtensions:
  datadog-lambda-js@*:
    peerDependencies:
      aws-sdk: ^2.831.0

# .. rest of the config ..
```

**Comment by tianchu** [comment]
Closing due the lack of activity (check this [article](https://docs.datadoghq.com/serverless/guide/serverless_tracing_and_webpack/) if you still have issue with webpack)
