### ISSUE TITLE
How to debug "datadog:handler not initialized"

### ISSUE THREAD

**Issue by devshorts** [DataDog/datadog-lambda-js#209]
## Expected Behavior
Not getting this error

## Actual Behavior
Getting `datadog:handler not initialized` logged in my lambdas. Whats weird is that I am getting metrics though. I don't care about traces or anything else, I just wanted to send custom metrics to datadog from the lambda.

Also the lambda got significantly slower pulling this layer in and emitting distribution metrics. Is that because its timing out trying to connect to something? I would have expected that the extension running as a process sidecar should make it so that the lambda can execute as fast as normal since its emitting async to the sidecar?

Look at the resulting graphs when I deployed the distrubtion metrics to my lambda 

![image](https://user-images.githubusercontent.com/1799346/128221979-3728b88c-3325-4178-bfff-d480ef392f1b.png)

## Steps to Reproduce the Problem

  1. I have the datadog extension layer set up for my lambda and my lambdas wrapped with `datadog(.. my handler...)`. I am not using the setup of 
```
Set your function’s handler to /opt/nodejs/node_modules/datadog-lambda-js/handler.handler if using the layer, or node_modules/datadog-lambda-js/dist/handler.handler if using the package.
Set the environment variable DD_LAMBDA_HANDLER to your original handler, for example, myfunc.handler.
```
Because I am webpacking the lambda into a single file, and couldn't figure out how to get the handler to be executed properly since webpack flattens it all. Not sure if that matters or not

## Specifications

  - Datadog Lambda Layer version: 9
  - Node version: 14

**Comment by tianchu** [comment]
@devshorts Thanks for reporting the issue!

Webpack does have some issues with `dd-trace` and some [special configurations](https://docs.datadoghq.com/serverless/troubleshooting/serverless_tracing_and_webpack) are required. Also did you follow the [instructions](https://docs.datadoghq.com/serverless/installation/nodejs)? 

Regarding the duration increase, please see the [explanation](https://docs.datadoghq.com/serverless/libraries_integrations/extension/#overhead). But in short, the extension duration is reported as part of the duration metric, but it does not delay your function's response from being returned to the client. Also see [AWS blog post](https://aws.amazon.com/blogs/compute/performance-and-functionality-improvements-for-aws-lambda-extensions/).

Since your issue is more like a support case that demands a closer look at your specific set up, I'm going to close this issue and recommend you get help either from our [Slack community](https://github.com/DataDog/datadog-lambda-js#community) or support@datadoghq.com.

**Comment by aterreno** [comment]
I am getting this issue as well, I did follow the guideline with the webpack externals, but still getting this every so often.

**Comment by comfortablynumb** [comment]
We've been having this issue. We're using the serverless framework + webconfig. The problem was that the **datadog-lambda-js** library was being included in the deployed lambda even after adding what's describe [here](https://docs.datadoghq.com/serverless/troubleshooting/serverless_tracing_and_webpack/) (**forceExclude** datadog-lambda-js). 

I believe this was caused because the [serverless-webpack](https://github.com/serverless-heaven/serverless-webpack) plugin was **not** removing the **datadog-lambda-js** library which, in our case, was a direct dependency and also a transitive dependency (one library we use had datadog-lambda-js also as a dependency). After some research, we've found that this plugin does not support the exclusion of transitive dependencies as shown in [this issue](https://github.com/serverless-heaven/serverless-webpack/issues/306).

The solution was to remove the dependency manually with a script entry like this:

```
custom:
  webpack:
    packagerOptions:
      scripts:
        - rm -rf node_modules/datadog-lambda-js
```

There must be a better way to solve this, but in our case this fixed the issue.

Hope this helps!

**Comment by tianchu** [comment]
Thanks @CorruptedHeart! I will add a note to our [doc](https://docs.datadoghq.com/serverless/guide/serverless_tracing_and_webpack/).

**Comment by tianchu** [comment]
https://github.com/DataDog/documentation/pull/14028

**Comment by alvaroseparovich** [comment]
My team were struggling with this for a bit, but using the **Serverless Framework**  and **Lambda** with **NodeJs**.

we followed [this instructions](https://docs.datadoghq.com/serverless/installation/nodejs/?tab=serverlessframework), but to follow it locally, obviously, we installed the 2 packages that are in the tutorial, and it worked, but deployed to AWS we couldn't use the package datadog-labda-js to call the function `sendDistributionMetric` as it is in the tutorial, we were receiving the same error `{ "status": "error",  "message": "datadog:handler not initialized" }`
Then I saw we installed this dependencies not in devDependencies, so I moved this dd-trace and datadog-lambda-js to devDependecies, it was sufficient to solve the error.

**Comment by paco-sparta** [comment]
# To whomever comes in the future

`"datadog-lambda-js` and `dd-trace` are injected by the environment, so any version you submit won't be configured and will error with what's on the title.

This means you have to either:

* exclude it from your bundler, like the messages above
* add it to your "devDependencies" for the simplest scripts.

**Comment by ib-jamesp** [comment]
Just going to leave this here for the future: if you have the call to `sendMetrics` wrapped in an async method, make sure you have awaited it... 👍 as it can also produce intermittent `datadog:handler not initialized` error.

**Comment by MikeyHermannSunPower** [comment]
Leaving my solution here that took me days to figure out: 
This was a versioning issue for me. I updated to the latest version of "aws-cdk", "datadog-cdk-constructs-v2", and "datadog-lambda-js", and made sure it was in the project-level(highest-level) package.json of my Node.js project, and it fixed it for me.
