### ISSUE TITLE
AWS Cloudformation Transform macro is adding two datadog layers , my deployment is running out due to codesize issue for lambda with these two layers

### ISSUE THREAD

**Issue by irfanahmed24** [DataDog/datadog-lambda-js#493]
AWS Cloudformation Transform macro is adding two datadog layers , my deployment is running out due to codesize issue for lambda with these two layers

**Comment by irfanahmed24** [comment]
do we need both these layers for nodejs lambda , Please advise

arn:aws:lambda:us-east-1:464622532012:layer:Datadog-Node18-x:96
arn:aws:lambda:us-east-1:464622532012:layer:Datadog-Extension:47

**Comment by astuyve** [comment]
Hi, yes both layers are required for the default setup.

Although this library isn't the [cloudformation macro project](https://github.com/DataDog/datadog-cloudformation-macro), the macro does seem to be working correctly here. One layer provides the tracing capability, the other is our Lambda Extension which ships logs, metrics, traces, profile data, and security signals back to datadog.

You can use the datadog lambda log forwarder instead of the datadog lambda extension if you'd rather. This can save about 30mb. [More information is here](https://docs.datadoghq.com/serverless/guide/extension_motivation/).

If you're running out of space in due to dependencies, verify that you're not inadvertently packaging development-only dependencies into your application. You can inspect your `node_modules` directory and run something like `du -hk | sort -n` to see the list in size-order.

Finally if you're sure you need every dependency you are currently packagine, you may consider using container images instead of zip-based Lambda functions. This will increase the max from 250mb to a whopping 10gb, and [substantially improve cold starts](https://aaronstuyvenberg.com/posts/containers-on-lambda).

Hope that helps!

**Comment by irfanahmed24** [comment]
Hi , Thank you for quick reply . we want to collect traces for our lambdas . My Lambda code  size is around 30MB it says . Can you please tell me what is the size of those two layers .

arn:aws:lambda:us-east-1:464622532012:layer:Datadog-Node18-x:96
arn:aws:lambda:us-east-1:464622532012:layer:Datadog-Extension:47

Thanks
irfan

**Comment by astuyve** [comment]
You can verify the layer sizes yourself following the [documentation](https://docs.datadoghq.com/serverless/guide/serverless_package_too_large/). Both layers combined are around 50mb now. If your code is only 30mb, that leaves 170mb unaccounted for.

I'd suggest downloading the zip file itself from the Lambda console and inspecting it.
