### ISSUE TITLE
Documentation request | Add a CHANGELOG to the root of the project for automated dependencies to pick up the changes 

### ISSUE THREAD

**Issue by juancarlosjr97** [DataDog/datadog-lambda-js#528]
This is just a request for tools such as Renovate to pick up the CHANGELOG and add release notes to the version of the project updated.

This would be great for the consumers :)

**Comment by juancarlosjr97** [comment]
I can raise the first MR for it, and if you want to automate as much as possible you can use release-it, changesets, or any other tools around!

**Comment by astuyve** [comment]
Hey @juancarlosjr97 - thanks for the note!
We publish release notes with every release, and you can find them [here](https://github.com/DataDog/datadog-lambda-js/releases) in the project.

Is there something else you'd prefer to see?

Thanks!

**Comment by juancarlosjr97** [comment]
Hey @astuyve :)

Yes, the release notes are great! However, tools such as Renovate pick up the information from a CHANGELOG file within a repo.

It will not have any information different to the release note that you are already doing.

**Comment by astuyve** [comment]
Hi @juancarlosjr97,

I took a look at the [tips for maintainers](https://docs.renovatebot.com/key-concepts/changelogs/#advice-for-package-maintainers) which is published by Renovate and it seems this should work out of the box. The [documentation](https://docs.renovatebot.com/key-concepts/changelogs/#how-renovate-detects-changelogs) says it will handle parsing metadata from GitHub Releases, and it can [easily strip the leading v from our versions](https://docs.renovatebot.com/modules/versioning/node/). We mostly follow semantic versioning (we do publish a lot of minor releases due to Lambda layer versioning), so I'm not sure what else we'd do here.

Given that I haven't use Renovate, I'm not sure I can offer specific advice, but I'd probably suggest looking at their [troubleshooting docs](https://docs.renovatebot.com/key-concepts/changelogs/#troubleshooting-missing-changelogs) as a starting point.

As for this issue, I don't intend to add a `Changelog.md` file because our group is responsible for nearly a dozen open source project and are trying to keep things standardized. If other users request this in the future, we can revisit the suggestion.

Thanks!
