### ISSUE TITLE
DD_SERVICE not showing in APM service list

### ISSUE THREAD

**Issue by heretogo** [DataDog/datadog-lambda-js#99]
## Expected Behavior
Expected behaviour is for "servicename" to appear in our service list in APM.

## Actual Behavior
"servicename" appears as a resource of the aws.lambda service.

Documentation is contradictory and not clear (https://docs.datadoghq.com/tracing/serverless_functions/?tab=nodejs#organizing-your-serverless-infrastructure-with-tags):

```
By default, each Lambda function is treated as its own service. Add your own tag to override this.

Note: The default behavior for new Datadog customers is for all Lambda functions to be grouped under the aws.lambda service, and represented as a single node on the Service map. Tag your functions by service to override this.
```

## Steps to Reproduce the Problem
Our lambda function is instrumented with the datadog-lambda-js library, configured with DD_SERVICE="servicename" and shipped using aws-dd-forwarder-3.14.0.zip. The forwarder is deployed manually and configured with the DD_FETCH_LAMBDA_TAGS=true. 

A variant that I tried was to use DD_TAGS=service:servicename.

"servicename" is using the library handler instead of the Lambda layer.

## Specifications

  - Datadog Lambda Layer version: "datadog-lambda-js": "^3.29.0"
  - Node version: Node.js 12.x

**Comment by tianchu** [comment]
Hi @heretogo we are currently going through a major refresh of our docs, and here is the latest one about tagging https://docs.datadoghq.com/serverless/serverless_tagging?tab=serverlessframework. TL;DR; we recommend you add a `service` and `env` tag to your Lambda function, instead of using environment variables like `DD_SERVICE`.

**Comment by heretogo** [comment]
Keep in mind that we are not using the Serverless framework. As such, I do not have access to the `.yaml` config shown as examples in the doc page you linked to.

In my specific use case should add the `service` and `env` tags via the environment using the `DD_TAGS` envar? Or is there another way.

**Comment by tianchu** [comment]
You don't need to use the Serverless Framework, you just need to tag your function (see AWS doc https://docs.aws.amazon.com/lambda/latest/dg/configuration-tags.html) with a `service` and `env` using whatever the way you manage/deploy your Lambda function.

Make sure you enable `DD_FETCH_LAMBDA_TAGS` by updating the CFN stack, rather than adding the environment variable directly, because the CFN stack adds additional permissions to the Forwarder Lambda function so it can fetch the tags from your Lambda functions and apply them to traces when they are forwarded.

**Comment by heretogo** [comment]
Ah, so it is AWS Resource tags. Do you happen to know which permissions are required? It is easier for us to manage without using CFN so I'd like to try and avoid redeploying the forwarder.

**Comment by heretogo** [comment]
This is resolved for me.
